//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoJungle.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoJungle.Resource.cn", typeof(cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏结束自动关闭.
        /// </summary>
        internal static string AutoClose {
            get {
                return ResourceManager.GetString("AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱台湾S7-自动打野.
        /// </summary>
        internal static string AutoJungle {
            get {
                return ResourceManager.GetString("AutoJungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soresu原作 | LOVETAIWAN更新 v.
        /// </summary>
        internal static string AutoJungleInfo2 {
            get {
                return ResourceManager.GetString("AutoJungleInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合成血手/战士后F5，挂机则会无法使用!.
        /// </summary>
        internal static string AutoJungleInfo3 {
            get {
                return ResourceManager.GetString("AutoJungleInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to reload the assembly (F5)!.
        /// </summary>
        internal static string AutoJungleInfoReload {
            get {
                return ResourceManager.GetString("AutoJungleInfoReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Zhi Chi Ci Ying Xiong!.
        /// </summary>
        internal static string ChampNotSupported {
            get {
                return ResourceManager.GetString("ChampNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用惩戒.
        /// </summary>
        internal static string ComboSmite {
            get {
                return ResourceManager.GetString("ComboSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制台显示调试信息.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试.
        /// </summary>
        internal static string dsettings {
            get {
                return ResourceManager.GetString("dsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启挂机.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入侵敌方野区.
        /// </summary>
        internal static string EnemyJungle {
            get {
                return ResourceManager.GetString("EnemyJungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gank次数.
        /// </summary>
        internal static string GankFrequency {
            get {
                return ResourceManager.GetString("GankFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低等级进行Gank.
        /// </summary>
        internal static string GankLevel {
            get {
                return ResourceManager.GetString("GankLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索范围.
        /// </summary>
        internal static string GankRange {
            get {
                return ResourceManager.GetString("GankRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gank设置.
        /// </summary>
        internal static string gsettings {
            get {
                return ResourceManager.GetString("gsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血量%使用药水.
        /// </summary>
        internal static string HealthToPotion {
            get {
                return ResourceManager.GetString("HealthToPotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回城血量(%).
        /// </summary>
        internal static string HealtToBack {
            get {
                return ResourceManager.GetString("HealtToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 野区设置.
        /// </summary>
        internal static string jsettings {
            get {
                return ResourceManager.GetString("jsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lsetting {
            get {
                return ResourceManager.GetString("lsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di Tu Bu Zhi Chi!.
        /// </summary>
        internal static string MapNotSupported {
            get {
                return ResourceManager.GetString("MapNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni mei you Cheng Jie/Zhong Ji!.
        /// </summary>
        internal static string NoSmite {
            get {
                return ResourceManager.GetString("NoSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner Spells.
        /// </summary>
        internal static string sssettings {
            get {
                return ResourceManager.GetString("sssettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示游戏状态.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持的英雄.
        /// </summary>
        internal static string supported {
            get {
                return ResourceManager.GetString("supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寡妇.
        /// </summary>
        internal static string supportedEvelyn {
            get {
                return ResourceManager.GetString("supportedEvelyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武器大师.
        /// </summary>
        internal static string supportedJax {
            get {
                return ResourceManager.GetString("supportedJax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梦魇.
        /// </summary>
        internal static string supportedNocturne {
            get {
                return ResourceManager.GetString("supportedNocturne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 龙女.
        /// </summary>
        internal static string supportedShyvana {
            get {
                return ResourceManager.GetString("supportedShyvana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛮王.
        /// </summary>
        internal static string supportedTryndamere {
            get {
                return ResourceManager.GetString("supportedTryndamere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷霆咆哮.
        /// </summary>
        internal static string supportedVolibear {
            get {
                return ResourceManager.GetString("supportedVolibear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狼人.
        /// </summary>
        internal static string supportedWarwick {
            get {
                return ResourceManager.GetString("supportedWarwick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赵信.
        /// </summary>
        internal static string supportedXinZhao {
            get {
                return ResourceManager.GetString("supportedXinZhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 易大师.
        /// </summary>
        internal static string supportedYi {
            get {
                return ResourceManager.GetString("supportedYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Barrier.
        /// </summary>
        internal static string UseBarrier {
            get {
                return ResourceManager.GetString("UseBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Heal.
        /// </summary>
        internal static string UseHeal {
            get {
                return ResourceManager.GetString("UseHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ignite.
        /// </summary>
        internal static string UseIgnite {
            get {
                return ResourceManager.GetString("UseIgnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Change focus if ignite kills.
        /// </summary>
        internal static string UseIgniteOpt {
            get {
                return ResourceManager.GetString("UseIgniteOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用饰品.
        /// </summary>
        internal static string UseTrinket {
            get {
                return ResourceManager.GetString("UseTrinket", resourceCulture);
            }
        }
    }
}
