//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortAIO.Resources.AutoJungle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortAIO.Resources.AutoJungle.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close at the end.
        /// </summary>
        internal static string AutoClose {
            get {
                return ResourceManager.GetString("AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S7-AutoJungle.
        /// </summary>
        internal static string AutoJungle {
            get {
                return ResourceManager.GetString("AutoJungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soresu | Updated by LOVETAIWAN v.
        /// </summary>
        internal static string AutoJungleInfo2 {
            get {
                return ResourceManager.GetString("AutoJungleInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to reload the assembly (F5)!.
        /// </summary>
        internal static string AutoJungleInfoReload {
            get {
                return ResourceManager.GetString("AutoJungleInfoReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This champion is not supported!.
        /// </summary>
        internal static string ChampNotSupported {
            get {
                return ResourceManager.GetString("ChampNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Smite.
        /// </summary>
        internal static string ComboSmite {
            get {
                return ResourceManager.GetString("ComboSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print to console.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string dsettings {
            get {
                return ResourceManager.GetString("dsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go into enemy jungle.
        /// </summary>
        internal static string EnemyJungle {
            get {
                return ResourceManager.GetString("EnemyJungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganking frequency.
        /// </summary>
        internal static string GankFrequency {
            get {
                return ResourceManager.GetString("GankFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min level to gank.
        /// </summary>
        internal static string GankLevel {
            get {
                return ResourceManager.GetString("GankLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching range.
        /// </summary>
        internal static string GankRange {
            get {
                return ResourceManager.GetString("GankRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gank settings.
        /// </summary>
        internal static string gsettings {
            get {
                return ResourceManager.GetString("gsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP% to use potion.
        /// </summary>
        internal static string HealthToPotion {
            get {
                return ResourceManager.GetString("HealthToPotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall on HP(%).
        /// </summary>
        internal static string HealtToBack {
            get {
                return ResourceManager.GetString("HealtToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle settings.
        /// </summary>
        internal static string jsettings {
            get {
                return ResourceManager.GetString("jsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lsetting {
            get {
                return ResourceManager.GetString("lsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map is not supported!.
        /// </summary>
        internal static string MapNotSupported {
            get {
                return ResourceManager.GetString("MapNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have smite!.
        /// </summary>
        internal static string NoSmite {
            get {
                return ResourceManager.GetString("NoSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner Spells.
        /// </summary>
        internal static string sssettings {
            get {
                return ResourceManager.GetString("sssettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show GameState.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported champions.
        /// </summary>
        internal static string supported {
            get {
                return ResourceManager.GetString("supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evelynn.
        /// </summary>
        internal static string supportedEvelyn {
            get {
                return ResourceManager.GetString("supportedEvelyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jax.
        /// </summary>
        internal static string supportedJax {
            get {
                return ResourceManager.GetString("supportedJax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayle.
        /// </summary>
        internal static string supportedKayle {
            get {
                return ResourceManager.GetString("supportedKayle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KogMaw.
        /// </summary>
        internal static string supportedKogMaw {
            get {
                return ResourceManager.GetString("supportedKogMaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nocturne.
        /// </summary>
        internal static string supportedNocturne {
            get {
                return ResourceManager.GetString("supportedNocturne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunu.
        /// </summary>
        internal static string supportedNunu {
            get {
                return ResourceManager.GetString("supportedNunu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olaf.
        /// </summary>
        internal static string supportedOlaf {
            get {
                return ResourceManager.GetString("supportedOlaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shyvana.
        /// </summary>
        internal static string supportedShyvana {
            get {
                return ResourceManager.GetString("supportedShyvana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryndamere.
        /// </summary>
        internal static string supportedTryndamere {
            get {
                return ResourceManager.GetString("supportedTryndamere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udyr.
        /// </summary>
        internal static string supportedUdyr {
            get {
                return ResourceManager.GetString("supportedUdyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volibear.
        /// </summary>
        internal static string supportedVolibear {
            get {
                return ResourceManager.GetString("supportedVolibear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warwick.
        /// </summary>
        internal static string supportedWarwick {
            get {
                return ResourceManager.GetString("supportedWarwick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin Zhao.
        /// </summary>
        internal static string supportedXinZhao {
            get {
                return ResourceManager.GetString("supportedXinZhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Yi.
        /// </summary>
        internal static string supportedYi {
            get {
                return ResourceManager.GetString("supportedYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Barrier.
        /// </summary>
        internal static string UseBarrier {
            get {
                return ResourceManager.GetString("UseBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Heal.
        /// </summary>
        internal static string UseHeal {
            get {
                return ResourceManager.GetString("UseHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ignite.
        /// </summary>
        internal static string UseIgnite {
            get {
                return ResourceManager.GetString("UseIgnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change focus if ignite kills.
        /// </summary>
        internal static string UseIgniteOpt {
            get {
                return ResourceManager.GetString("UseIgniteOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Trinket.
        /// </summary>
        internal static string UseTrinket {
            get {
                return ResourceManager.GetString("UseTrinket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for smite at level 2(HP 55% Lower).
        /// </summary>
        internal static string WaitAtLvlTWO {
            get {
                return ResourceManager.GetString("WaitAtLvlTWO", resourceCulture);
            }
        }
    }
}
