using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using EloBuddy; 
 using LeagueSharp.Common; 
 namespace Jhin_As_The_Virtuoso {
	public static class MultiLanguage {

		public static Dictionary<string, string> EnglishDictionary => new Dictionary<string, string>{
			{"戏命师 - 烬", "Jhin As The Virtuoso"},
			{ "走砍设置","Orbwalker"},
			{ "Q设置","Q Settings"},
			{ "可Q死小兵时消耗","Q Kill minions to harass enemy"},
			{ "一直用Q消耗","awalys Q harass"},
			{ "使用Q清兵","Q lanclear"},
			{ "使用Q补刀","Q Farm"},
			{ "Q抢人头","Q KS"},
			{ "W设置","W Settings"},
			{ "自动W硬控敌人","Auto W CC"},
			{ "W有标记的敌人","W enemy who has W mark"},
			{ "W抢人头","W KS"},
			{ "W有标记的突进","W anti marked gapcloser"},
			{ "敌人位移W","W marked dashing enemy"},
			{ "E设置","E Settings"},
			{ "自动E硬控敌人","Auto E CC"},
			{ "自动E防突进","E Antigap"},
			{ "自动E持续技能敌人","E Interrupt"},
			{ "敌人进草自动E","E Bush Revealer"},
			{ "敌人位移到看不到的地方E","E dashing enemy"},
			{ "使用E清兵","E lanclear"},
			{ "R设置","R Settings"},
			{ "移动设置","Move Settings"},
			{ "R时禁止移动和攻击","Disable move/attack when R is casting"},
			{ "当?码敌人靠近解除禁止","Enable move/attack when enemy distence ?"},
			{ "击杀提示设置","Kill Remind"},
			{ "文字提示R可击杀目标","Text Remind"},
			{ "文字提示横向位置","Text Position X"},
			{ "文字提示纵向位置","Text Position Y"},
			{ "信号提示R可击杀目标(本地)","Local Ping Remind"},
			{ "半手动R设置","Semi-manual cast R key"},
			{ "半手动R(自动R)","KeyBind"},
			{ "第一次R后延迟(毫秒)","Delay Before R2(ms)"},
			{ "第二次R后延迟(毫秒)","Delay Before R3(ms)"},
			{ "第三次R后延迟(毫秒)","Delay Before R4(ms)"},
			{ "R时无视野放蓝眼","Auto bule ward when RCasting and target miss"},
			{ "其它设置","Misc Settings"},
			{ "自动加点设置","AutoLevel Settings"},
			{ "只自动学大","Auto Level up R"},
			{ "自动加点","Enable Auto Level up"},
			{ "从几级开始加点","Start Level"},
			{ "加点延迟","Delay before Level up"},
			{ "加点方案","Level Sequence"},
			{ "主Q副W","Q-W-E"},
			{ "主Q副E","Q-E-W"},
			{ "主W副Q","W-Q-E"},
			{ "主W副E","W-E-Q"},
			{ "主E副Q","E-Q-W"},
			{ "主E副W","E-W-Q"},
			{ "9级时自动买蓝眼","Auto Buy Bule Ward"},
			{ "显示设置","Draw Settings"},
			{ "范围显示","Show Range"},
			{ "显示W范围","W Range"},
			{ "小地图显示W范围","W Range Minimap"},
			{ "显示E范围","E Range"},
			{ "显示R范围","R Range"},
			{ "小地图显示R范围","R Range Minimap"},
			{ "伤害提示","Damage Indicator"},
			{ "显示四次大招后伤害","Show 4R Damage"},
			{ "调试","Debug"},
			{ "E名单","E List"},
			{ "W名单","W List"},
			{ "E名单只适用于防突进/位移","E List only for Anti Gapcloser/dashing enemy"},
			{ "你付了钱，就好好看戏吧","Start the music，I will make then dance"},
			{ "Language Settings","语言设置"},
			{ "Press F5 reload assebmly to change language","按F5重载脚本更换语言"},
			{  "Select language","选择语言"},
			{ "自动R设置","Auto R Settings"},
			{ "自动R","Auto R"},
			{ "",""},
			//{ "",""},
		};
	}
}
